### ISSUE TITLE
Epic | Move to Cloud

### ISSUE THREAD

**Issue by kdavletov-exadel** [SergiLomtadze/SERGI_LOMTADZE_INDIVIDUAL_MENTORSHIP#129]
- [ ] Dockerize Auth app
- [ ] Deploy to cloud (CI/CD). If Azure, see your options
- [ ] Use cloud IAM instead of Auth. If Azure, then AAD
- [ ] Federate cloud IAM with your Auth server
- [ ] Federate cloud IAM with Exadel Identity Provider
- [ ] Kubernetes
